Toast notifikace
cesko-digital/app pull request #1092
Opened 2024-08-31 20:06 UTC by drahoja9

Close #1080

2024-09-10 06:43 UTC, zoul requested changes
Cool! Vizuálně se mně to moc líbí a věcně je super, žes to nacpal přímo do té sdílené cesty přes `useResourse`, takže to automaticky funguje všude.

My jsme mezitím trochu ujeli s masterem 😅, mohl bys to prosím rebasnout? A u textových inputů jsme se nakonec shodli, že bychom chtěli to explicitní chování, nikoliv automatické ukládání. Můžeš tedy to automatické ukládání zrušit? A můžem do produkce.

Díky moc!

2024-09-10 09:03 UTC, drahoja9 commented
Jasné, rebasnu a textové inputy vrátím do původní podoby. 🙂

2024-09-11 12:40 UTC, anezkamll commented
@drahoja9 Kubo, chtěla jsem se jen zeptat, jestli se k tomu dostaneš ještě dnes nebo zítra, nebo až později?
Naplánovaal bych si podle toho nahrání onboarding videa.

2024-09-11 14:43 UTC, zoul commented
Wow, zajímavý! Děje se to i na produkci. Moc nechápu, v tu chvíli na komponenta vůbec neposílá `onChange`. W–T–F? Co rychle googluju, vypadá to, že `onChange` není úplně spolehlivý event.

2024-09-12 06:48 UTC, merged