Konfigurace ukladani zmen v nastaveni profilu do databaze
cesko-digital/app pull request #1096
Opened 2024-09-07 10:08 UTC by laurabaluchova

Musela som pridat nejake nastavenia aby sa vsetky nove policka prepisovali pri zmenach do databaze

2024-09-08 10:10 UTC, laurabaluchova commented
@zoul mala som cas tak som to rovno fixla tak ze pouzivam komponentu pre input s ukladacim tlacitko, medzery zjednotene :) mrkni, testovala som aj funkcnost vyzera ze vsetko bezi ako ma...

2024-09-09 08:49 UTC, zoul requested changes
Ten hotfix jsem vytáhl bokem a hodil rovnou do masteru, můžeš prosím zkusit rebase jen s tím refactoringem inputů nad aktuálním masterem? (Kdyby to vypadalo složitě, řekni.)

2024-09-09 13:37 UTC, zoul commented
Změnil jsem ještě tyhle věci:

Podle mě je lepší, když API té komponenty `InputWithSaveButton` už neví nic o tom nadřazeném modelu. Ideální je, když je to prostě komponenta pro řetězce. Tím je obecnější a líp se přizpůsobuje změnám v kódu.

Validaci e-mailů taky navrhuju zobecnit, tedy neřešit ji přímo v `InputWithSaveButton`, ale nabídnout pro ni rovnou API, například v podobě property `validator`, která bere funkci `(value: string) => string | undefined` (kde `undefined` znamená „bez chyb“). Jednak se tím trochu vyčistí kód komponenty, jednak se to dá snadno použít i pro další věci.

Dává ti to takhle smysl, když si pročteš ty moje změny? Jestli jo, můžem ještě naposledy otestovat a můžem mergnout.

2024-09-09 16:09 UTC, laurabaluchova commented
@zoul super, presla som, vyzera to dobre, profesionalnejsie :D, aj som otestovala a vsetky zmeny mi hned ulozilo :) akurat ti tam visi jeden console.log

2024-09-10 06:33 UTC, zoul commented
Slova „profesionálnější“ bych se tu trochu bál :), ale mergujeme! :rocket:

2024-09-10 06:35 UTC, merged